
export const BladeProjectData = [
    {
        id: 1,
        project_name: "Josie",
        customer: "McDermott, O'Hara and Stanton",
        project_leader: "Arri",
        start_date: "17/08/2023",
        end_date: "07/05/2023",
    },
    {
        id: 2,
        project_name: "Mauricio",
        customer: "Leffler Group",
        project_leader: "Bevon",
        start_date: "08/06/2023",
        end_date: "30/08/2023",
    },
    {
        id: 3,
        project_name: "Tiffie",
        customer: "McLaughlin, Farrell and Hagenes",
        project_leader: "Chrotoem",
        start_date: "31/08/2023",
        end_date: "12/02/2023",
    },
    {
        id: 4,
        project_name: "Sidonia",
        customer: "Romaguera-Bauch",
        project_leader: "Walton",
        start_date: "21/12/2022",
        end_date: "17/11/2022",
    },
    {
        id: 5,
        project_name: "Shalne",
        customer: "Deckow-Stehr",
        project_leader: "Chase",
        start_date: "04/11/2023",
        end_date: "03/04/2023",
    },
    {
        id: 6,
        project_name: "Binky",
        customer: "Lowe-Rolfson",
        project_leader: "Agustin",
        start_date: "02/03/2023",
        end_date: "21/01/2023",
    },
    {
        id: 7,
        project_name: "Danika",
        customer: "Goodwin-Kertzmann",
        project_leader: "Erich",
        start_date: "24/05/2023",
        end_date: "02/08/2023",
    },
    {
        id: 8,
        project_name: "Wallis",
        customer: "Pacocha-Harber",
        project_leader: "Bogey",
        start_date: "04/01/2023",
        end_date: "06/05/2023",
    },
    {
        id: 9,
        project_name: "Cecelia",
        customer: "Reilly-Pacocha",
        project_leader: "Stanleigh",
        start_date: "09/06/2023",
        end_date: "24/01/2023",
    },
    {
        id: 10,
        project_name: "Zahara",
        customer: "Bauch LLC",
        project_leader: "Asher",
        start_date: "13/09/2023",
        end_date: "23/05/2023",
    },
    {
        id: 11,
        project_name: "Patty",
        customer: "Smitham Inc",
        project_leader: "Orland",
        start_date: "15/06/2023",
        end_date: "17/09/2023",
    },
    {
        id: 12,
        project_name: "Cammie",
        customer: "Morar-Stark",
        project_leader: "Yuma",
        start_date: "28/06/2023",
        end_date: "11/03/2023",
    },
    {
        id: 13,
        project_name: "Chalmers",
        customer: "Keeling Inc",
        project_leader: "Dennison",
        start_date: "27/07/2023",
        end_date: "07/01/2023",
    },
    {
        id: 14,
        project_name: "Tracie",
        customer: "Pollich-Haley",
        project_leader: "Boote",
        start_date: "13/11/2022",
        end_date: "10/10/2023",
    },
    {
        id: 15,
        project_name: "Goldarina",
        customer: "Stanton-Bogisich",
        project_leader: "Bondon",
        start_date: "18/09/2023",
        end_date: "03/11/2023",
    },
    {
        id: 16,
        project_name: "Crichton",
        customer: "Haag-Glover",
        project_leader: "Steward",
        start_date: "07/07/2023",
        end_date: "01/09/2023",
    },
    {
        id: 17,
        project_name: "Carmine",
        customer: "Hudson, Mayert and Hegmann",
        project_leader: "Seward",
        start_date: "11/05/2023",
        end_date: "22/07/2023",
    },
    {
        id: 18,
        project_name: "Gabie",
        customer: "Becker LLC",
        project_leader: "Nichole",
        start_date: "06/03/2023",
        end_date: "13/03/2023",
    },
    {
        id: 19,
        project_name: "Renell",
        customer: "Johnston Inc",
        project_leader: "Skell",
        start_date: "16/07/2023",
        end_date: "01/07/2023",
    },
    {
        id: 20,
        project_name: "Emilee",
        customer: "Wolf, Thompson and Tremblay",
        project_leader: "Gerard",
        start_date: "12/11/2022",
        end_date: "23/04/2023",
    },
    {
        id: 21,
        project_name: "Bliss",
        customer: "Koch and Sons",
        project_leader: "Conroy",
        start_date: "18/08/2023",
        end_date: "10/01/2023",
    },
    {
        id: 22,
        project_name: "Alisander",
        customer: "Yundt-Bins",
        project_leader: "Grantley",
        start_date: "11/03/2023",
        end_date: "07/03/2023",
    },
    {
        id: 23,
        project_name: "Marilyn",
        customer: "Bernhard, Roob and Huel",
        project_leader: "Colin",
        start_date: "12/05/2023",
        end_date: "23/12/2022",
    },
    {
        id: 24,
        project_name: "Lorenza",
        customer: "Leuschke, Brakus and Heller",
        project_leader: "Caspar",
        start_date: "02/01/2023",
        end_date: "01/08/2023",
    },
    {
        id: 25,
        project_name: "Anatollo",
        customer: "Towne-Walter",
        project_leader: "Ferd",
        start_date: "04/08/2023",
        end_date: "26/03/2023",
    },
    {
        id: 26,
        project_name: "Donnie",
        customer: "Lehner, Mraz and Hamill",
        project_leader: "Kort",
        start_date: "25/01/2023",
        end_date: "04/03/2023",
    },
    {
        id: 27,
        project_name: "Grady",
        customer: "Armstrong-Schneider",
        project_leader: "Elnar",
        start_date: "16/06/2023",
        end_date: "07/03/2023",
    },
    {
        id: 28,
        project_name: "Lainey",
        customer: "Welch-Kreiger",
        project_leader: "Randal",
        start_date: "18/08/2023",
        end_date: "08/10/2023",
    },
    {
        id: 29,
        project_name: "Jarad",
        customer: "Spencer, Dietrich and Cole",
        project_leader: "Kerwinn",
        start_date: "27/01/2023",
        end_date: "17/12/2022",
    },
    {
        id: 30,
        project_name: "Bailey",
        customer: "Moen, Lebsack and Rath",
        project_leader: "Clevey",
        start_date: "27/03/2023",
        end_date: "10/10/2023",
    },
    {
        id: 31,
        project_name: "Pamella",
        customer: "Prosacco, Kovacek and Glover",
        project_leader: "Cirilo",
        start_date: "15/09/2023",
        end_date: "21/10/2023",
    },
    {
        id: 32,
        project_name: "Nicki",
        customer: "Hagenes-Rodriguez",
        project_leader: "Guglielmo",
        start_date: "28/11/2022",
        end_date: "05/01/2023",
    },
    {
        id: 33,
        project_name: "Romy",
        customer: "Buckridge, Farrell and Rice",
        project_leader: "Jeremy",
        start_date: "01/12/2022",
        end_date: "08/12/2022",
    },
    {
        id: 34,
        project_name: "Jada",
        customer: "Collins, Lindgren and King",
        project_leader: "Guthrey",
        start_date: "14/10/2023",
        end_date: "06/01/2023",
    },
    {
        id: 35,
        project_name: "Martainn",
        customer: "Williamson-Wiza",
        project_leader: "Allard",
        start_date: "28/10/2023",
        end_date: "17/10/2023",
    },
    {
        id: 36,
        project_name: "Sophey",
        customer: "Mueller-Rogahn",
        project_leader: "Shermy",
        start_date: "24/01/2023",
        end_date: "12/06/2023",
    },
    {
        id: 37,
        project_name: "Lilia",
        customer: "Huel-Spencer",
        project_leader: "Dew",
        start_date: "09/01/2023",
        end_date: "19/06/2023",
    },
    {
        id: 38,
        project_name: "Heriberto",
        customer: "Schulist and Sons",
        project_leader: "Garek",
        start_date: "12/11/2022",
        end_date: "31/03/2023",
    },
    {
        id: 39,
        project_name: "Leeann",
        customer: "Durgan, Turner and White",
        project_leader: "Ingrim",
        start_date: "16/12/2022",
        end_date: "13/07/2023",
    },
    {
        id: 40,
        project_name: "Debbi",
        customer: "Schuppe, Gulgowski and Abshire",
        project_leader: "Griswold",
        start_date: "16/09/2023",
        end_date: "10/12/2022",
    },
    {
        id: 41,
        project_name: "Isabeau",
        customer: "Fay and Sons",
        project_leader: "Rufus",
        start_date: "03/01/2023",
        end_date: "20/11/2022",
    },
    {
        id: 42,
        project_name: "Timmie",
        customer: "Glover-Corwin",
        project_leader: "Haleigh",
        start_date: "21/08/2023",
        end_date: "17/10/2023",
    },
    {
        id: 43,
        project_name: "Wendall",
        customer: "Legros Inc",
        project_leader: "Donavon",
        start_date: "30/09/2023",
        end_date: "05/10/2023",
    },
    {
        id: 44,
        project_name: "Bathsheba",
        customer: "Bernhard, Jerde and Cassin",
        project_leader: "Pauly",
        start_date: "16/06/2023",
        end_date: "15/03/2023",
    },
    {
        id: 45,
        project_name: "Lionel",
        customer: "Miller Inc",
        project_leader: "Delainey",
        start_date: "02/06/2023",
        end_date: "11/07/2023",
    },
    {
        id: 46,
        project_name: "Nada",
        customer: "Paucek, Adams and Weimann",
        project_leader: "Mata",
        start_date: "01/02/2023",
        end_date: "23/05/2023",
    },
    {
        id: 47,
        project_name: "Lock",
        customer: "Welch Inc",
        project_leader: "Bogey",
        start_date: "28/09/2023",
        end_date: "19/04/2023",
    },
    {
        id: 48,
        project_name: "Toiboid",
        customer: "Cummerata-Emmerich",
        project_leader: "Thorvald",
        start_date: "22/01/2023",
        end_date: "25/05/2023",
    },
    {
        id: 49,
        project_name: "Cherry",
        customer: "Quitzon, Cartwright and Dibbert",
        project_leader: "Garvy",
        start_date: "04/07/2023",
        end_date: "06/06/2023",
    },
];

export type BladeProject = (typeof BladeProjectData)[number];
