export const EquipmentData = [
    { id: 1, type: "Excavator" },
    { id: 2, type: "Trencher" },
    { id: 3, type: "Crawler" },
    { id: 4, type: "Backhoe" },
    { id: 5, type: "Crawler" },
    { id: 6, type: "Excavator" },
    { id: 7, type: "Excavator" },
    { id: 8, type: "Backhoe" },
    { id: 9, type: "Scraper" },
    { id: 10, type: "Backhoe" },
    { id: 11, type: "Compactor" },
    { id: 12, type: "Dragline" },
    { id: 13, type: "Grader" },
    { id: 14, type: "Compactor" },
    { id: 15, type: "Scraper" },
    { id: 16, type: "Excavator" },
    { id: 17, type: "Excavator" },
    { id: 18, type: "Dump Truck" },
    { id: 19, type: "Grader" },
    { id: 20, type: "Grader" },
    { id: 21, type: "Crawler" },
    { id: 22, type: "Grader" },
    { id: 23, type: "Excavator" },
    { id: 24, type: "Excavator" },
    { id: 25, type: "Skid-Steer" },
    { id: 26, type: "Compactor" },
    { id: 27, type: "Backhoe" },
    { id: 28, type: "Scraper" },
    { id: 29, type: "Bulldozer" },
    { id: 30, type: "Dragline" },
    { id: 31, type: "Dragline" },
    { id: 32, type: "Backhoe" },
    { id: 33, type: "Trencher" },
    { id: 34, type: "Compactor" },
    { id: 35, type: "Compactor" },
    { id: 36, type: "Dragline" },
    { id: 37, type: "Compactor" },
    { id: 38, type: "Excavator" },
    { id: 39, type: "Grader" },
    { id: 40, type: "Dump Truck" },
    { id: 41, type: "Bulldozer" },
    { id: 42, type: "Scraper" },
    { id: 43, type: "Dump Truck" },
    { id: 44, type: "Compactor" },
    { id: 45, type: "Scraper" },
    { id: 46, type: "Skid-Steer" },
    { id: 47, type: "Backhoe" },
    { id: 48, type: "Scraper" },
    { id: 49, type: "Scraper" },
    { id: 50, type: "Bulldozer" },
];

export type EquipmentData = (typeof EquipmentData)[number];
